// 此文件由 DebugxCodeGenerator 自动生成，请勿手动修改。
// Auto-generated by DebugxCodeGenerator. Do not modify manually.
// HideInCallstack 特性可以隐藏调用栈中的此方法，方便查看调用者。必须在 Console 窗口中点击设置后勾选 “Strip logging callstack” 后才能生效。
// The HideInCallstack attribute can hide this method from the call stack, making it easier to see the caller. 
// It only takes effect after checking "Strip logging callstack" in the Console window settings.
// 使用 Logger 结尾的类名可以在双击 Console 窗口的日志时在此类为止阻断，方便查看调用 Log 的业务逻辑位置。
// Class names ending with Logger can block at this class when double-clicking logs in the Console window, 
// making it easier to see the business logic location that called Log.

#if !DEBUGX_IN_UPM
using System.Diagnostics;
using DebugxLog;
using UnityEngine;

public static class DebugxLogger
{
    /// <summary>
    /// Log for member [Normal] (Key: -1).
    /// 成员 [Normal] 的 Log 方法 (Key: -1)。
    /// </summary>
    [Conditional("DEBUG_X"), HideInCallstack]
    public static void LogNormal(object message, bool showTime = false, bool showNetTag = false)
    {
        Debugx.Log(-1, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogWarning for member [Normal] (Key: -1).
    /// 成员 [Normal] 的 LogWarning 方法 (Key: -1)。
    /// </summary>
    [Conditional("DEBUG_X"), HideInCallstack]
    public static void LogWarningNormal(object message, bool showTime = false, bool showNetTag = false)
    {
        Debugx.LogWarning(-1, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogError for member [Normal] (Key: -1).
    /// 成员 [Normal] 的 LogError 方法 (Key: -1)。
    /// </summary>
    [Conditional("DEBUG_X"), HideInCallstack]
    public static void LogErrorNormal(object message, bool showTime = false, bool showNetTag = false)
    {
        Debugx.LogError(-1, message, showTime, showNetTag);
    }

    /// <summary>
    /// Log for member [Master] (Key: -2).
    /// 成员 [Master] 的 Log 方法 (Key: -2)。
    /// </summary>
    [Conditional("DEBUG_X"), HideInCallstack]
    public static void LogMaster(object message, bool showTime = false, bool showNetTag = false)
    {
        Debugx.Log(-2, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogWarning for member [Master] (Key: -2).
    /// 成员 [Master] 的 LogWarning 方法 (Key: -2)。
    /// </summary>
    [Conditional("DEBUG_X"), HideInCallstack]
    public static void LogWarningMaster(object message, bool showTime = false, bool showNetTag = false)
    {
        Debugx.LogWarning(-2, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogError for member [Master] (Key: -2).
    /// 成员 [Master] 的 LogError 方法 (Key: -2)。
    /// </summary>
    [Conditional("DEBUG_X"), HideInCallstack]
    public static void LogErrorMaster(object message, bool showTime = false, bool showNetTag = false)
    {
        Debugx.LogError(-2, message, showTime, showNetTag);
    }

    /// <summary>
    /// Log for member [Blur] (Key: 1).
    /// 成员 [Blur] 的 Log 方法 (Key: 1)。
    /// </summary>
    [Conditional("DEBUG_X"), HideInCallstack]
    public static void LogBlur(object message, bool showTime = false, bool showNetTag = false)
    {
        Debugx.Log(1, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogWarning for member [Blur] (Key: 1).
    /// 成员 [Blur] 的 LogWarning 方法 (Key: 1)。
    /// </summary>
    [Conditional("DEBUG_X"), HideInCallstack]
    public static void LogWarningBlur(object message, bool showTime = false, bool showNetTag = false)
    {
        Debugx.LogWarning(1, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogError for member [Blur] (Key: 1).
    /// 成员 [Blur] 的 LogError 方法 (Key: 1)。
    /// </summary>
    [Conditional("DEBUG_X"), HideInCallstack]
    public static void LogErrorBlur(object message, bool showTime = false, bool showNetTag = false)
    {
        Debugx.LogError(1, message, showTime, showNetTag);
    }

}
#endif
