// Auto-generated by DebugxCodeGenerator. Do not modify manually.
// 此文件由 DebugxCodeGenerator 自动生成，请勿手动修改。

#if !DEBUGX_IN_UPM
using DebugxLog;

public class Debugx : DebugxBase
{
    /// <summary>
    /// Log for member [Normal] (Key: -1).
    /// 成员 [Normal] 的 Log 方法 (Key: -1)。
    /// </summary>
    public static void LogNormal(object message, bool showTime = false, bool showNetTag = false)
    {
        Log(-1, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogWarning for member [Normal] (Key: -1).
    /// 成员 [Normal] 的 LogWarning 方法 (Key: -1)。
    /// </summary>
    public static void LogWarningNormal(object message, bool showTime = false, bool showNetTag = false)
    {
        LogWarning(-1, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogError for member [Normal] (Key: -1).
    /// 成员 [Normal] 的 LogError 方法 (Key: -1)。
    /// </summary>
    public static void LogErrorNormal(object message, bool showTime = false, bool showNetTag = false)
    {
        LogError(-1, message, showTime, showNetTag);
    }

    /// <summary>
    /// Log for member [Master] (Key: -2).
    /// 成员 [Master] 的 Log 方法 (Key: -2)。
    /// </summary>
    public static void LogMaster(object message, bool showTime = false, bool showNetTag = false)
    {
        Log(-2, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogWarning for member [Master] (Key: -2).
    /// 成员 [Master] 的 LogWarning 方法 (Key: -2)。
    /// </summary>
    public static void LogWarningMaster(object message, bool showTime = false, bool showNetTag = false)
    {
        LogWarning(-2, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogError for member [Master] (Key: -2).
    /// 成员 [Master] 的 LogError 方法 (Key: -2)。
    /// </summary>
    public static void LogErrorMaster(object message, bool showTime = false, bool showNetTag = false)
    {
        LogError(-2, message, showTime, showNetTag);
    }

    /// <summary>
    /// Log for member [Blur] (Key: 1).
    /// 成员 [Blur] 的 Log 方法 (Key: 1)。
    /// </summary>
    public static void LogBlur(object message, bool showTime = false, bool showNetTag = false)
    {
        Log(1, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogWarning for member [Blur] (Key: 1).
    /// 成员 [Blur] 的 LogWarning 方法 (Key: 1)。
    /// </summary>
    public static void LogWarningBlur(object message, bool showTime = false, bool showNetTag = false)
    {
        LogWarning(1, message, showTime, showNetTag);
    }

    /// <summary>
    /// LogError for member [Blur] (Key: 1).
    /// 成员 [Blur] 的 LogError 方法 (Key: 1)。
    /// </summary>
    public static void LogErrorBlur(object message, bool showTime = false, bool showNetTag = false)
    {
        LogError(1, message, showTime, showNetTag);
    }

}
#endif
