using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace DebugxLog.Editor
{
    /// <summary>
    /// Code generator for Debugx class.
    /// Automatically generates member-specific Log methods based on DebugxProjectSettingsAsset configuration.
    /// 为 Debugx 类自动生成代码。
    /// 根据 DebugxProjectSettingsAsset 配置自动生成成员专用的 Log 方法。
    /// </summary>
    public static class DebugxLoggerCodeGenerator
    {
        private const string DebugxClassPath = "Assets/Plugins/Debugx/Runtime/DebugxLogger.cs";
        
        // Regex to validate C# identifier (method name). Unicode-aware so non-ASCII signatures (e.g. 中文) also generate methods.
        // 校验 C# 标识符（方法名）。支持 Unicode，使中文等非 ASCII 签名也能生成便捷方法。
        private static readonly Regex _validIdentifierRegex = new Regex(@"^[\p{L}_][\p{L}\p{Mn}\p{Mc}\p{Nd}\p{Pc}]*$");

        /// <summary>
        /// Generate Debugx.cs file with member-specific Log methods.
        /// 生成包含成员专用 Log 方法的 Debugx.cs 文件。
        /// </summary>
        public static void GenerateDebugxLoggerClass()
        {
            var settingsAsset = DebugxProjectSettingsAsset.Instance;
            if (!settingsAsset)
            {
                Debug.LogWarning("[DebugxCodeGenerator] DebugxProjectSettingsAsset not found.");
                return;
            }

            StringBuilder sb = new StringBuilder();
            // Holds the FINAL method names already emitted (Log*/LogWarning*/LogError*), not just suffixes, so
            // dedup catches cross-family collisions (see GetUniqueMethodSuffix).
            // 保存已生成的【最终方法名】（Log*/LogWarning*/LogError*）而非仅后缀，使去重能捕获跨方法族的撞名（见 GetUniqueMethodSuffix）。
            HashSet<string> usedMethodNames = new HashSet<string>();
            
            // File header
            sb.AppendLine("// 此文件由 DebugxCodeGenerator 自动生成，请勿手动修改。");
            sb.AppendLine("// Auto-generated by DebugxCodeGenerator. Do not modify manually.");
            sb.AppendLine("// HideInCallstack 特性可以隐藏调用栈中的此方法，方便查看调用者。必须在 Console 窗口中点击设置后勾选 “Strip logging callstack” 后才能生效。");
            sb.AppendLine("// The HideInCallstack attribute can hide this method from the call stack, making it easier to see the caller. \n// It only takes effect after checking \"Strip logging callstack\" in the Console window settings.");
            sb.AppendLine("// 使用 Logger 结尾的类名可以在双击 Console 窗口的日志时在此类为止阻断，方便查看调用 Log 的业务逻辑位置。");
            sb.AppendLine("// Class names ending with Logger can block at this class when double-clicking logs in the Console window, \n// making it easier to see the business logic location that called Log.");
            sb.AppendLine();
            sb.AppendLine("#if !DEBUGX_IN_UPM");
            sb.AppendLine("using System.Diagnostics;");
            sb.AppendLine("using DebugxLog;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("public static class DebugxLogger");
            sb.AppendLine("{");

            // Generate methods for default members
            if (settingsAsset.defaultMemberAssets != null)
            {
                foreach (var member in settingsAsset.defaultMemberAssets)
                {
                    GenerateMemberMethods(sb, member, usedMethodNames);
                }
            }

            // Generate methods for custom members
            if (settingsAsset.customMemberAssets != null)
            {
                foreach (var member in settingsAsset.customMemberAssets)
                {
                    GenerateMemberMethods(sb, member, usedMethodNames);
                }
            }

            sb.AppendLine("}");
            sb.AppendLine("#endif");
            
            // Write to file
            string absolutePath = Path.Combine(Application.dataPath, "..", DebugxClassPath);
            string directory = Path.GetDirectoryName(absolutePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            string newContent = sb.ToString();
            
            // Check if content changed
            if (File.Exists(absolutePath))
            {
                string existingContent = File.ReadAllText(absolutePath);
                if (existingContent == newContent)
                {
                    return; // No changes needed
                }
            }

            File.WriteAllText(absolutePath, newContent, Encoding.UTF8);
            AssetDatabase.Refresh();
            
            Debug.Log("[DebugxCodeGenerator] Debugx.cs generated successfully.");
        }

        /// <summary>
        /// Generate Log, LogWarning, LogError methods for a member.
        /// 为成员生成 Log、LogWarning、LogError 方法。
        /// </summary>
        private static void GenerateMemberMethods(StringBuilder sb, DebugxMemberInfoAsset member, HashSet<string> usedMethodNames)
        {
            if (string.IsNullOrEmpty(member.signature))
                return;

            string methodSuffixBase = SanitizeMethodName(member.signature);
            if (string.IsNullOrEmpty(methodSuffixBase))
                return;

            string methodSuffix = GetUniqueMethodSuffix(methodSuffixBase, member.signature, usedMethodNames);
            int key = member.key;

            // Log method
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Log for member [{member.signature}] (Key: {key}).");
            sb.AppendLine($"    /// 成员 [{member.signature}] 的 Log 方法 (Key: {key})。");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    [Conditional(\"DEBUG_X\"), HideInCallstack]");
            sb.AppendLine($"    public static void Log{methodSuffix}(object message, bool showTime = false, bool showNetTag = false)");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        Debugx.Log({key}, message, showTime, showNetTag);");
            sb.AppendLine($"    }}");
            sb.AppendLine();

            // LogWarning method
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// LogWarning for member [{member.signature}] (Key: {key}).");
            sb.AppendLine($"    /// 成员 [{member.signature}] 的 LogWarning 方法 (Key: {key})。");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    [Conditional(\"DEBUG_X\"), HideInCallstack]");
            sb.AppendLine($"    public static void LogWarning{methodSuffix}(object message, bool showTime = false, bool showNetTag = false)");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        Debugx.LogWarning({key}, message, showTime, showNetTag);");
            sb.AppendLine($"    }}");
            sb.AppendLine();

            // LogError method
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// LogError for member [{member.signature}] (Key: {key}).");
            sb.AppendLine($"    /// 成员 [{member.signature}] 的 LogError 方法 (Key: {key})。");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    [Conditional(\"DEBUG_X\"), HideInCallstack]");
            sb.AppendLine($"    public static void LogError{methodSuffix}(object message, bool showTime = false, bool showNetTag = false)");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        Debugx.LogError({key}, message, showTime, showNetTag);");
            sb.AppendLine($"    }}");
            sb.AppendLine();
        }

        /// <summary>
        /// Sanitize signature to be a valid C# method name.
        /// 将签名转换为有效的 C# 方法名。
        /// </summary>
        private static string SanitizeMethodName(string signature)
        {
            if (string.IsNullOrEmpty(signature))
                return null;

            // Remove spaces and invalid characters
            StringBuilder sb = new StringBuilder();
            bool capitalizeNext = false;
            
            foreach (char c in signature)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    if (capitalizeNext && char.IsLetter(c))
                    {
                        // ToUpperInvariant，避免 char.ToUpper 随机器区域变化（土耳其 locale 下 'i'→'İ' U+0130），
                        // 使生成的方法名不随开发者机器 locale 漂移、引发跨机器编译不一致。
                        // Use ToUpperInvariant so the generated method name doesn't drift with the machine locale
                        // (Turkish 'i' -> 'İ' U+0130), which would cause cross-machine compile mismatches.
                        sb.Append(char.ToUpperInvariant(c));
                        capitalizeNext = false;
                    }
                    else
                    {
                        sb.Append(c);
                    }
                }
                else if (c == ' ' || c == '-' || c == '.')
                {
                    // Use PascalCase for spaces/dashes/dots
                    capitalizeNext = true;
                }
            }

            string result = sb.ToString();
            
            // Ensure it doesn't start with a digit
            if (result.Length > 0 && char.IsDigit(result[0]))
            {
                result = "_" + result;
            }

            // Validate the result
            if (string.IsNullOrEmpty(result) || !_validIdentifierRegex.IsMatch(result))
            {
                Debug.LogWarning($"[DebugxCodeGenerator] Cannot generate method for signature '{signature}' - invalid identifier.");
                return null;
            }

            return result;
        }

        private static string GetUniqueMethodSuffix(string methodSuffixBase, string signature, HashSet<string> usedMethodNames)
        {
            // Dedup on the FINAL method names of all three families (Log*/LogWarning*/LogError*), not just the suffix.
            // A suffix that is unique on its own can still collide across families: signature "Foo" emits LogWarningFoo
            // (Warning family) while signature "Warning Foo" -> suffix "WarningFoo" emits LogWarningFoo (Log family) —
            // same method name, causing CS0111 in the generated file. Bump the suffix until all three names are free.
            // 按三族的【最终方法名】（Log*/LogWarning*/LogError*）去重，而非仅后缀。后缀本身唯一仍可能跨族撞名：
            // 签名 "Foo" 生成 LogWarningFoo（Warning 族），而签名 "Warning Foo" 的后缀 "WarningFoo" 其 Log 族也生成 LogWarningFoo，
            // 两者同名 → 生成文件报 CS0111。递增后缀直到三个名字都空闲。
            string methodSuffix = methodSuffixBase;
            int counter = 2;
            while (!AreMethodNamesFree(usedMethodNames, methodSuffix))
            {
                methodSuffix = $"{methodSuffixBase}_{counter}";
                counter++;
            }

            usedMethodNames.Add("Log" + methodSuffix);
            usedMethodNames.Add("LogWarning" + methodSuffix);
            usedMethodNames.Add("LogError" + methodSuffix);

            if (!string.Equals(methodSuffix, methodSuffixBase))
            {
                Debug.LogWarning($"[DebugxCodeGenerator] Signature '{signature}' generated duplicate method name. Renamed to '{methodSuffix}'.");
            }

            return methodSuffix;
        }

        // Whether all three family method names (Log/LogWarning/LogError + suffix) are still unused.
        // 三族方法名（Log/LogWarning/LogError + 后缀）是否都尚未使用。
        private static bool AreMethodNamesFree(HashSet<string> usedMethodNames, string methodSuffix)
        {
            return !usedMethodNames.Contains("Log" + methodSuffix)
                && !usedMethodNames.Contains("LogWarning" + methodSuffix)
                && !usedMethodNames.Contains("LogError" + methodSuffix);
        }

        /// <summary>
        /// Menu item to manually regenerate Debugx.cs.
        /// 手动重新生成 Debugx.cs 的菜单项。
        /// </summary>
        [MenuItem("Tools/Debugx/Regenerate DebugxLogger Class")]
        public static void RegenerateDebugxClass()
        {
            GenerateDebugxLoggerClass();
        }
    }
}
